### PR TITLE
Store parents also

### PR DESCRIPTION
**Pull request by analyticd**
This is major update that makes a lot of changes. Don't feel compelled to integrate it if you don't care for it. I like it, but I can of course keep using it on my own repo.

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Could you provide a summary of what this does? I see that you added Brainparents, among other things. What is the purpose?

**Comment by analyticd** [comment]
Kungsgeten, I recommend skipping this one. It works great and solves many bugs, etc., but I have another branch I am working on that is not compatible with this one. Better just to wait for that one or not integrate it into org-brain on your repo and just let it live on a branch. To get the details for this one though, it is detailed in the README and in commit messages.

**Comment by Kungsgeten** [comment]
Ok, exciting :) I'd be happy to discuss the future of `org-brain` via e-mail, please send me a message at sjostrand.erik@gmail.com

I have some questions regarding the caching, but feel it would be more convenient to discuss them via mail vs random Github threads :)

**Comment by Kungsgeten** [comment]
I'm removing the pull requests, since they're probably not applicable for version 0.4. You seem to have contributed some nice features and fixes though, so I'll try to look into those and see if they can be applied to the new version.

**Pull request closed without merging**
