### PR TITLE
Prettify buffer

### PR DESCRIPTION
**Pull request by yuhan0**
- Makes the org-brain buffer read-only by default
- Defines separate faces for the title, parents, child, friend and pinned entries, as well as the "wires" between entries
- Adds an option to disable the max-title-length setting in mind-map mode, set to /not/ truncate by default.

The default face attributes are set to 
- gigantic title
- bold parents, no differentiation between entries otherwise
- light yellow colored wires

which are of course open for change, these just happen to be my personal settings :)

Shown below with the spacemacs-dark theme and unicode wires
image

A few things to consider:
- Using different font size for the title messes up the alignment of multiple friend entries.
- I chose to use the "child" face for siblings, since they appear as child nodes of parents in the visualization. Would there be a need for a separate `org-brain-sibling` face?
- Similarly, should the Resources and Entry subtitles, and resource link buttons also be fontified?

Thanks for this awesome package! 😄

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! This looks great! I'll have to test it first, but it looks ready to merge.

I think we might as well add `org-brain-sibling` face. It can simply inherit the child face by default. I also think it is wise if `org-brain-title` simply inherits from some other face which looks like a title. Perhaps something from `org-mode`? Most themes support `org-mode` by default, so it will look nice in most configurations without the user changing anything. I'm not sure if we can do the same with `org-brain-wires`, but perhaps its okay if they just inherit the default face (or perhaps `highlight`)? I think `org-brain-pinned` could also inherit from something in `org-mode`, but to me personally I don't think they need to have a larger font height.

The `org-brain--insert-wire` function might as well have a docstring, even if it is just a very simple function.

Do we really need to have the faces as optional arguments to the various functions? Are there cases where we don't want to supply the face? Perhaps I haven't read the code enough, but to me it seems most logical just always using the face.

I do not quite think this fixes #125 . That user seems to want different faces depending on if the entries are file entries or headline entries (but I might have misunderstood).

Thank you very much for your contribution! Also sorry for the lack of updates recently, hopefully I'll have more time for my emacs packages in the future :)

**Comment by yuhan0** [comment]
Thanks for the reply, I made some of the suggested changes - if you're happy with them I'll go ahead and squash them into the previous commits.  :)
- Title inherits from `org-level-1`
- Wires inherit from `font-lock-comment-face`,  I realised yellow would not show up well on light themes. 
- parents inherit from `font-lock-builtin-face` ( I find that a bit of visual distinction with the color helps especially in "mind-map" mode) 
- pinned entries look normal (I don't actually use pins myself, not sure why I had them enlarged in the first place)

> Do we really need to have the faces as optional arguments to the various functions? Are there cases where we don't want to supply the face?
The only function signature I changed was for `org-brain-insert-visualize-button`, and it defaults to using the org-brain-button face if none is supplied. 

I might have misunderstood #125, will remove from the title so the issue won't get closed automatically.

**Comment by Kungsgeten** [comment]
So I've finally gotten around to try this out. It seems to work for the most part. For me though the only character that gets the `org-brain-wires` face property is the ▽ character. The other part of the wire have no text properties when I use `M-x describe-char`.

I realize now that the reason for this is that I use `aa2u` (ascii-art-to-unicode) which converts all other wire characters in the buffer. I have this code:

```
(use-package ascii-art-to-unicode
    :config
    (defun aa2u-buffer ()
      (aa2u (point-min) (point-max)))
    (add-hook 'org-brain-after-visualize-hook #'aa2u-buffer))
```

When I remove `aa2u-buffer` from the hook it works fine. It would be nice to find to still use the text properties, and at the same time use aa2u. However I'll go ahead and merge this, since aa2u isn't a part of `org-brain`. Thanks!

**Comment by Kungsgeten** [comment]
Cool, nice work! I've now added that to the README. Why do you think the entry text should be marked as aa2u-text?

**Comment by yuhan0** [comment]
For example it mangles links with dashes in them, turning them into the unicode "─"

image 
(clicking the blue link on the right takes you to https://github.com/Kungsgeten/org%E2%94%80brain/issues , also note the truncated block end header)

Org tables might look better, but in general wouldn't it make sense to leave entry text alone?

**Comment by Kungsgeten** [comment]
The `org-brain-after-visualize-hook` is run before inserting `org-brain-text`. If you put the aa2u functions there you shouldn't get this problem (it works for me). It might make sense to mark it as aa2u-text anyway though. Perhaps you're using `org-brain-visualize-text-hook`, which is run after inserting the entry text?

**Pull request merged**
