### PR TITLE
speedup org-brain-visualize

### PR DESCRIPTION
**Pull request by tumashu**
1. speedup: org-brain-visualize is slow in my machine for big org files, I add cache feature with the help of async, which let org-brain-visualize very fast.
2. Using read function to org-brain-data-file , more secure.
3. Add org-brain-headline-entries-match: used to filter headline
4. Add org-brain-files-match: used to filter file
5. Add org-brain-files-transparent : used to filter file, but the file's headlines work as usual

### CODE REVIEW

**Comment by tumashu** [comment]
@Kungsgeten The change of org-brain have finished, please review and comment, thanks!

**Comment by Kungsgeten** [comment]
Hi! Sorry for the delay with this review. Since the changes are pretty big I'll have to look at it some day when I have the appropriate chunk of spare time :)

**Comment by tumashu** [comment]
OK, I try hard to merge org-brain to my workflow, but not success at the moment, I have many many headlines, so the origin is very very slow, so I add org-brain-cache to let speed fast, but, the new problem is that how to let org-brain-cache update in time， this seem to be a not a simple thing as I though :-(


Maybe org-brain is not a good tool to manage headlines,  it is a very very good tool to manage 
tags, the reason is that:
1.  Tags are not too much， so speed is not problem
2. Tags  are  the concept of a thing mostly, so  org-brain them more useful

**Comment by yuhan0** [comment]
Hi @tumashu , just an observation and some advice here - this PR in its current state looks pretty messy, plenty of the commits are completely unrelated to speeding up org-brain-visualize, and from your last comment it sounds like you're unsure if it even works properly? 
I know most project maintainers would refuse to accept or look at a large code-dump like this - you'd have a much better chance of having it reviewed if you split the changes up into separate PRs, each one tackling a separate issue.

**Comment by Kungsgeten** [comment]
@tumashu This PR is very big and I don't quite understand what it does. If you still think it is relevant, maybe you could break it down into smaller parts?

**Comment by tumashu** [comment]
@Kungsgeten Just ignore this PR at the moment, Now I think that  using async to deal with org-brain-visualize's speed may not a proper way.

**Comment by Kungsgeten** [comment]
I'm closing this since the work on it seems to be dormant. Feel free to open it again when/if you feel its ready to be implemented.

**Comment by tumashu** [comment]
ok!

**Pull request closed without merging**
