### PR TITLE
Stay the same button when select.

### PR DESCRIPTION
**Pull request by tumashu**
* org-brain.el (org-brain-jump-to-button): New function.
(org-brain-select): Stay the same button when select.

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! I like the idea! However I wonder if this shouldn't be the default of `org-brain--revert-if-visualizing`? I made a version like this, which seems to work:

```
(defun org-brain--revert-if-visualizing ()
  "Revert buffer if in `org-brain-visualize-mode'."
  (when (eq major-mode 'org-brain-visualize-mode)
    (let ((button-entry-id (org-brain-entry-identifier
                            (car (org-brain-button-at-point)))))
      (org-brain-stop-wandering)
      (revert-buffer)
      (when button-entry-id
        (let ((char-target (point)))
          (goto-char (point-min))
          (search-forward "\n\n" nil t)
          (while (and (or (ignore-errors (forward-button 1))
                          (goto-char char-target))
                      (not (equal (button-get (button-at (point)) 'id)
                                  button-entry-id)))))))))
```

Maybe its nice to have the goto entry button as a function though.

**Comment by tumashu** [comment]
good idea too :-)

**Comment by Kungsgeten** [comment]
I made some modifications to the code above and commited it. I hope you don't mind. Thank you for the suggestion!

**Comment by tumashu** [comment]
:-) no problem, just just it.



At 2020-02-29 18:55:44, "Erik Sjöstrand" <notifications@github.com> wrote:

I made some modifications to the code above and commited it. I hope you don't mind. Thank you for the suggestion!

**Pull request closed without merging**
