### PR TITLE
Add no-siblings tag to prevent display of siblings, replace org-get-tags-at with org-get-tags, improve file renaming

### PR DESCRIPTION
**Pull request by drbronner**
This PR contains three orthogonal commits, which do the following:

- Implement a `:nosiblings:` tag, which suppresses the drawing of siblings in org-brain visualizations (updated version of #170).
- Replace calls to `org-get-tags-at` with calls to `org-get-tags`. `org-get-tags-at` has been obsolete for a while, and is starting to cause compilation problems with very recent versions of org.
- Improve `org-brain-rename-file` (updated version of #175).

Details on each of these commits is below.

If you'd prefer I can issue PRs for each commit, but my sense is that the code changes are easy enough to differentiate. Let me know if that's not true.

### The `:nosiblings:` tag

The feature is inspired by TheBrain's "type" nodes. In TheBrain, when you declare a node as a "type" node, siblings of children of that node are not drawn in the plex.

The idea here is that when an entry has a large number of children, the visualization blows up when a child of that entry is selected, because of the large list of siblings of the child entry. When the parent is tagged with :nosiblings:, these siblings are not drawn.

I have some reservations about the name "nosiblings", since we are actually suppressing child nodes of the :nosibling: node, but the point is to suppress siblings of a selected node, and a better name hasn't occurred to me.

Commit notes:

- If the current entry's parent has the no-siblings tag,
  the entry's siblings through that parent are not rendered during vis
- defcustom to specify the name of the tag to use.
  (Defaults to "nosiblings").

### Replacing `org-get-tags-at`

As above, this seems to be causing compilation problems in recent versions of org. `org-get-tags` seems to have identical functionality, and I have noticed no problems after the switch.

Commit notes:

org-get-tags-at is obsolete as of org 9.2

### Improve `org-brain-rename-file`

org-brain-rename-file currently fails in quite a bad way if the org-brain directory is under git version control. Within a git repo, renaming does the following:

- Remove relationships from the old-name file
- Copy the old-name file into a new-name file
- Delete the old-name file with vc-delete-file
- Add relationships to the new-name file

The problem is that vc-delete-file fails if the file to be deleted is dirty, which it generally is, since its relationships have been removed just prior to deletion. The failure occurs in the middle of the function, after links have been removed but before they have been added to the new file. This leaves the brain in an inconsistent state.

The solution is to use vc-rename-file, which succeeds with a dirty file. It also has the benefit of reliably recording the file rename in the git repo.

Other improvements to file rename include checking to make sure a buffer for the new file doesn't exist, which will cause the rename to fail; updating the pinned, selected, and history lists; and reverting the org-brain buffer after the rename, so that the renamed entry is immediately visible.

Commit notes:

- Rename the file rather than copying and deleting.
  This avoids problems trying to delete a dirty file under vc
- Add check for buffer associated with new file name.
  This will make vc-rename-file fail.
- Update entries in the pinned, selected, and history list properly.
- Update the currently visualized entry to account for file rename, if needed.
  Before, the old name would remain as the current entry.
- Revert the buffer after the file rename, so the renamed entry shows up.

### CODE REVIEW

**Comment by Kungsgeten** [comment]
I've been meaning to change to `org-get-tags` for a while, since I've noticed warnings (like you mention). The issue here is if I then need to update the dependencies of `org-brain`? Right now `org-brain` depend on org 9, but I don't think `org-get-tags-at` was made obsolete until org 9.2. In the release notes of org 9.2 it says:

> Function org-get-tags used to return local tags to the current headline. It now returns all the inherited tags in addition to the local tags. In order to get the old behaviour back, you can use:
> 
> (org-get-tags nil t)

So maybe we need to update the dependencies to org 9.2? I don't think that's a problem, just thinking about whether the newer dependency is needed.

**Comment by drbronner** [comment]
Ah good call. I've updated the PR to include a dependency on org 9.2.

**Comment by drbronner** [comment]
Also just updated the PR to add a sharp-quote to a mapcar param that I had forgotten.

**Comment by drbronner** [comment]
Added some code to make sure that the file is re-pinned and re-selected properly. Sorry for the force pushing.

**Comment by Kungsgeten** [comment]
Overall it looks good! I'll make some minor changes to the documentation and some of the code (see next commit). I also noticed a bug introduced by the vis-history thing: the history needs to be reset when using `org-brain-switch-brain`, so I'll fix that too.

I'll try to make the `nosiblings` tag work on file entries too.

**Comment by drbronner** [comment]
> Overall it looks good! I'll make some minor changes to the documentation and some of the code (see next commit). I also noticed a bug introduced by the vis-history thing: the history needs to be reset when using `org-brain-switch-brain`, so I'll fix that too.

Ah sorry about that — I haven't used multiple brains, so I didn't think about this.

I'm interested in starting a test suite. Have you given any thought to this?

> I'll try to make the `nosiblings` tag work on file entries too.

I have a later PR that adds an `org-brain-get-tags` function that generalizes getting tags to file entries, so if you haven't already done that work, I can reorder the history a bit and put a PR in for that right away. Let me know.

**Comment by drbronner** [comment]
Ah I see you've already put that in. No worries.

**Comment by Kungsgeten** [comment]
> I'm interested in starting a test suite. Have you given any thought to this?

Yes I think a test suite would be very useful. I haven't worked with tests when programming though (I probably should get into it) and I'm not sure how easy/hard it would be for `org-brain`. My main concern is that you'd need several org-files as part of the test suite, and also make sure that `org-id` works correctly when trying out the "test brain".

**Comment by drbronner** [comment]
I don't have much test experience either, but it's never too late to start!

I'll give it a look this week and might post some ramblings here.

**Pull request merged**
