### PR TITLE
* org-brain.el (org-brain-vis-title): delete-dups vis perpend and append functions.

### PR DESCRIPTION
**Pull request by tumashu**

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! I don't quite get the purpose of this. Why would you have duplicates in `org-brain-vis-title-prepend-functions` and the like? These variables holds a list of functions, so in order for `delete-dups` to do anything in this PR the user would have to have added the same function to the list twice. It could be though that I don't fully understand the change.

**Comment by tumashu** [comment]
```
(push 'eh-org-brain-entry-nicknames org-brain-vis-current-title-append-functions)
```

I have this  config in my emacs config, 
When I test my config,  eval-buffer twice will let org-brain show dups info, I have to manual deal with it.

**Comment by Kungsgeten** [comment]
If I remember correctly you could use `add-to-list` instead of `push`.

**Comment by tumashu** [comment]
good idea.

**Pull request closed without merging**
