### PR TITLE
Add =selected= list for bulk linking and unlinking.

### PR DESCRIPTION
**Pull request by drbronner**
This is an initial sketch for bulk-edit functionality. The idea is that you can select a bunch of thoughts, and then add the whole list as children, parents, or friends of a particular entry in one go. The patch introduces

* An `org-brain-selected` list, similar to the pinned list.
* Keybindings that add/remove entries to the selected list, and clear the selected list
* Functions that add and remove the selected entries as children, parents, or friends of an entry.

There is some refactoring that could be done because manipulating and displaying the pinned and selected lists is basically identical, but I'm not sure it's worth the effort.

The selected list does not persist between sessions.

At some point I'd like to add programmatic entry into the selected list.

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! Thanks for the PR! I'm abroad at the moment, so it'll take some time (probably the end of the month) before I can sit down properly and review it.

**Comment by Kungsgeten** [comment]
I've now tried it and I like it! I have some suggestions though, which I might implement. Please comment what you think about them :)

1. Change the keybinding of `org-brain-select` to `s`. Actually I don't find `;` to be a bad binding, its just that I don't use an American keyboard myself, so the `;` key is a lot more unintuitive for me (and maybe also others who use different keyboard layouts). The `s` key isn't used by `org-brain` right now, so I think it can be a good choice.

2. `org-brain-clear-selected` thus gets bound to `S`.

3. Maybe combine (or make a new command) `org-brain-select` and `org-brain-select-button` into one command? So if we're on a button it will select the button, otherwise it will select the visualized entry. I don't know if this is intuitive, but at least its one less button to learn :) Also maybe if you use the universal argument (like `C-u s`, because I guess this new command would replace `org-brain-select` in the keymap) then always select the visualized entry.

4. When using `org-brain-add-child` and similar (remove/add relationships) then if we have selected entries perhaps Emacs could ask "You have selected entries. Do you want to add/remove them?". If you choose yes, then the selected entries will be used, otherwise it uses the normal command (choose entry from a list). This way you could select some entries with `s` and then just press `c` (followed by `y` to confirm) to add them as children, for instance. Maybe a bit more convenient than to use `M-x` to find the right command? Another option could be to use a prefix key for all the `org-brain-add/remove-selected` commands.

**Comment by drbronner** [comment]
> I've now tried it and I like it! I have some suggestions though, which I might implement. Please comment what you think about them :)
> 
> 1. Change the keybinding of `org-brain-select` to `s`. Actually I don't find `;` to be a bad binding, its just that I don't use an American keyboard myself, so the `;` key is a lot more unintuitive for me (and maybe also others who use different keyboard layouts). The `s` key isn't used by `org-brain` right now, so I think it can be a good choice.
> 2. `org-brain-clear-selected` thus gets bound to `S`.

Yep, sounds good to me.

> 3. Maybe combine (or make a new command) `org-brain-select` and `org-brain-select-button` into one command? So if we're on a button it will select the button, otherwise it will select the visualized entry. I don't know if this is intuitive, but at least its one less button to learn :) Also maybe if you use the universal argument (like `C-u s`, because I guess this new command would replace `org-brain-select` in the keymap) then always select the visualized entry.

Yes I see what you mean. So to be clear, the idea is

- `s` selects the button under point, or the visualized entry if the point is not on a button
- `C-u s` always selects the visualized entry

Seems reasonable to me — I agree, having two keybindings for such a similar thing is a bit weird.

> 4. When using `org-brain-add-child` and similar (remove/add relationships) then if we have selected entries perhaps Emacs could ask "You have selected entries. Do you want to add/remove them?". If you choose yes, then the selected entries will be used, otherwise it uses the normal command (choose entry from a list). This way you could select some entries with `s` and then just press `c` (followed by `y` to confirm) to add them as children, for instance. Maybe a bit more convenient than to use `M-x` to find the right command? Another option could be to use a prefix key for all the `org-brain-add/remove-selected` commands.

Ah interesting. Yes I think it's a good idea. My intuition is that the prefix key would be better. I could see a situation where I keep a number of entries selected for some period of time, and I wouldn't want the work-horse commands like "add child" and "add parent" to suddenly start acting differently.

I would also suggest that we keep the commands selected-entry commands in the code base, and just have the prefixed versions of add-child et al call out to them, so that the selected-entry commands remain easy to discover. What do you think?

**Comment by Kungsgeten** [comment]
I've changed the bindings to `s` (for the new command `org-brain-select-dwim`) and all other selection commands (including clearing the selections) had been added to `org-brain-select-map` which is bound to `S`. So to add selected entries as children you would do `S c` (or `S C` to remove them). To clear the selection you do `S s` or `S S`. I've also added information to the README.

Thank you for this functionality!

**Comment by drbronner** [comment]
Ah, that's a great approach! Nice!

**Pull request merged**
