### PR TITLE
Consideration of ambiguous entry titles

### PR DESCRIPTION
**Pull request by robocad**
Dear Erik,
I've modified _org-brain-choose-entries_ to consider duplicate titles in file and headline entries.

Example:
file1.org #+TITLE: test
file2.org #+TITLE: test

Before the modification, all functions based on _org-brain-choose-entries_, such as _org-brain-goto_ would provide "test" for completion, but return only "file1" as ID.

I am aware, that a concept map preferably should not contain duplicate entries. However, in growing org-brain collections this could happen accidentally. With the change, a user would at least be informed about the ambiguity and can select a specific entry.

Best regards,
Robert

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! Sorry for not getting back to you sooner. I had missed that you submitted this.

Nice idea! I tried it out now, but noticed that even though it finds two entries with the same title, it will always return the same entry no matter what I choose. I had one file entry and one headline entry when trying this.

I think the issue is because of this line later: `(entry-path (org-brain-entry-path (car id) t))`. When `org-brain-entry-path` uses `t` for `check-title` .

**Comment by robocad** [comment]
Thanks for looking into it.

I think the behavior you describe comes from the `completing-read`. If you have a file entry "foo" and a headline entry "foo", org-brain prompts for "foo" and "foo::foo". Entering "foo" is not unique, but complete and returns "foo" (i.e., the file entry). For me, this case is acceptable, as I can still specifically enter "foo::foo" to access the headline entry.

The situation I address occurs with multiple files or headline entries with the same title. For example file1: "foo", file2: "foo". In this case org-brain prompts a single "foo" only, but there are two possible targets. Now the added code will kick in and asks the user to clarify (currently by adding the id). Without it, I have no chance to access the other entry using org-brain-choose-entries.

Best regards,
Robert

**Comment by user-b** [comment]
Hello. I was going to start a new "question" issue but it seems to be related to this one. 

I was wondering if org-brain can or could (optionally?)  name new files with a (..unique..) timestamp plus a given name, and also automatically add the given name as #+TITLE.

So for example if we have two hierarchies, one for chess and one for go, we could have two "#+TITLE: Games" files with all our games stored separatedly.

It seems to be how org-roam works.


Another nice related feature could be to show one-way edge annotations (or another similiar annotation) concatenated after titles both in org-brain-mind-map mode and the minibufer when searching files with org-brain-visualize. This could help a lot to quickly identify what is inside/under each node of a big collection, possibly with repeated (and confusing when not shown hierarchically) names/titles. In my (maybe poor) experience with collections of data, the structure somehow carries a lot of meaning and when the structure becomes big it's easy to forget for example why you gruped some seemingly unrelated pieces of  data six months ago. So labeling a hierarchy/collection with some easy to read notes seems to be the best solution to avoid the whole structure to become "unstable" when your (real) brain can't keep track of the purpose of each node without having to deeply re-analize all it's contents and put too much effort to remember the "train of thought" giving birth to each collection.

**Comment by Kungsgeten** [comment]
@user-b No, there's no builtin way to name files the way you want, nor to give entries an automatic title. Perhaps it could be added. I personally use the technique described under "Chronological entries with org-expiry" in the README to give timestamps to entries. I think annotations could be shown in entry titles with the `org-brain-vis-title-prepend-functions` or `org-brain-vis-title-append-functions` but I haven't experimented with it.

**Pull request closed without merging**
