### PR TITLE
Support for editing the org-brain-entry buffer

### PR DESCRIPTION
**Pull request by ryjm**
Updates the entry in the corresponding `.org` file when the
`org-brain-entry` is saved.

It's a bit hacky, but works for me.

### CODE REVIEW

**Comment by ryjm** [comment]
It opens a separate buffer for the entry text - not sure if everyone would want that, so maybe there should be an option to disable this feature.

**Comment by Kungsgeten** [comment]
Hi! If I understand correctly the idea is to get a separate buffer, where we can edit the entry text? In most entries I got an error (invalid buffer), probably because I had an empty entry text. I one where I had text the buffer appeared, but I didn't understand how to save my changes.

**Comment by ryjm** [comment]
Yup, that’s the idea (and you’re right about the invalid buffer, should definitely fix that).

It works pretty much the same as editing a src block in org mode - you just save the buffer like any normal buffer, and it will save it to the original file. Maybe a buffer header stating that would be useful?

Sorry I submitted this without it being completely ready for merging, just figured some people might want it sooner rather than later.

**Comment by Kungsgeten** [comment]
I got some kind of message when I tried to save the buffer, so it didn't work for me (or perhaps I did something wrong). I like the idea, but the coolest thing would probably be being able to modify the text directly from `org-brain-visualize`. I've thought about that, but haven't tried implementing it.

**Comment by Kungsgeten** [comment]
I get the following `Wrong-type-argument: integer-or-marker-p, nil`. Here's the output when I use `toggle-debug-on-error`:

```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  goto-char(nil)
  (save-current-buffer (set-buffer org-brain--source-buffer) (undo-boundary) (goto-char beg) (delete-region beg end) (insert "\n") (insert edited-text) (insert "\n") (setq end (point)) (save-buffer))
  (let ((edited-text (buffer-string)) (beg org-brain--vis-src-beg) (end org-brain--vis-src-end)) (save-current-buffer (set-buffer org-brain--source-buffer) (undo-boundary) (goto-char beg) (delete-region beg end) (insert "\n") (insert edited-text) (insert "\n") (setq end (point)) (save-buffer)) (setq org-brain--vis-src-end end))
  org-brain--vis-text-save()
  run-hook-with-args-until-success(org-brain--vis-text-save)
  basic-save-buffer(nil)
  save-buffer()
  save-buffer-no-trailing-ws()
  funcall-interactively(save-buffer-no-trailing-ws)
  call-interactively(save-buffer-no-trailing-ws nil nil)
  command-execute(save-buffer-no-trailing-ws)
```

I also got a char-related error when I tried to visualize one of my other entries.

**Comment by ryjm** [comment]
Oh I know! I only implemented it with headlines and not file entries. Try it on headline entries - should work. I’ll push a fix in a sec.

Later, I’ll clean this up a bit, add an option to enable/disable it, and resubmit.

**Comment by Kungsgeten** [comment]
Since this is pretty old and org-brain has changed a lot since then, I'm closing this. I think about the same functionalilty is provided by `org-brain-visualize-follow`.

**Pull request closed without merging**
