### PR TITLE
Indent for :RESOURCES: draws in entries

### PR DESCRIPTION
**Pull request by AmanYang**

### CODE REVIEW

**Comment by Kungsgeten** [comment]
Hi! I do not really understand what the pull request is about, could you please clarify?

**Comment by AmanYang** [comment]
Hi!
I found the RESOURCES drawer didn't indent properly when creating children.
I created the children in the same file as its parent. 
The right buffer in following image shows the differences after apply this patch. 

image

**Comment by Kungsgeten** [comment]
I'm sorry for this taking so long. I'm not very good at git, and there were merge conflicts because of me changing some code. However I've added your fix in a commit, and given you credit in the commit message. Is that ok?

**Comment by AmanYang** [comment]
:+1: Thanks for your work, Erik.

**Pull request closed without merging**
